export const DummyData = [
  { id: 1, beQuestion: '제 첫인상은 어땠나요?' },
  { id: 2, beQuestion: '저의 장점은 무엇인가요?' },
  { id: 3, beQuestion: '저의 단점은 무엇인가요?' },
  { id: 4, beQuestion: '나에게 어울리는 전공은 뭐야?' },
  { id: 5, beQuestion: '연예인 중 저의 닮은 꼴은 무엇인가요?' },
  { id: 6, beQuestion: '동물 중 저의 닮은 꼴은 무엇인가요?' },
  { id: 7, beQuestion: '저의 가장 큰 매력은 무엇일까요?' },
  { id: 8, beQuestion: '첫인상과 지금의 저는 어떻게 다른가요?' },
  { id: 9, beQuestion: '내가 만약 당신을 클럽에서 만났다면?' },
  { id: 10, beQuestion: '저를 한 단어로 정의하면 무엇일까요?' },
  { id: 11, beQuestion: '저에게 어울릴 것 같은 직업은 무엇인가요?' },
  { id: 12, beQuestion: '나에게 어울릴 것 같은 동아리는?' },
  { id: 13, beQuestion: '저에게 가장 고마웠던 일이 있다면 무엇이었나요?' },
  { id: 14, beQuestion: '저에게 가장 서운했던 일이 있다면 무엇이었나요?' },
  { id: 15, beQuestion: '저와 하루를 보낼 수 있다면 무엇을 같이 하고 싶나요?' },
  { id: 16, beQuestion: '저는 당신에게 어떤 사람이었나요?' },
  {
    id: 17,
    beQuestion: '저와 함께 했던 날 중 가장 기억에 남는 날은 언제였나요?',
  },
  { id: 18, beQuestion: '어느 날 제가 갑자기 바퀴벌레로 변한다면?' },
  {
    id: 19,
    beQuestion:
      '어느 날 제가 당신에게 갑자기 1,000만원을 준다면 당신의 반응은?',
  },
  {
    id: 20,
    beQuestion:
      '저를 만약 당신을 소개팅 자리에서 만났다면, 당신은 어떤 기분일까요?',
  },
  { id: 21, beQuestion: '저에게 어울리는 것 : 웜톤 Vs 쿨톤' },
  { id: 22, beQuestion: '저에게 어울리는 컬러는?' },
  { id: 23, beQuestion: '저에게 더 어울리는 옷은? 코트 Vs 패딩' },
  { id: 24, beQuestion: '저에게 어울리는 헤어 스타일은?' },
  { id: 25, beQuestion: '저에게 어울릴 것 같은 이성의 스타일은?' },
  { id: 26, beQuestion: '제 MBTI는 무엇일까요?' },
  { id: 27, beQuestion: '제가 좋아할 것 같은 음악은?' },
  { id: 28, beQuestion: '저에게 어울리는 음악은?' },
  { id: 29, beQuestion: '제가 잘할 것 같은 운동은?' },
  { id: 30, beQuestion: '제가 만약 당신의 가족이었다면?' },
  { id: 31, beQuestion: '저의 매력 포인트는 무엇인가요?' },
  { id: 32, beQuestion: '저에게 어울리는 향은 무엇인가요?' },
  { id: 33, beQuestion: '저에게 어울리는 것 : 외유내강 Vs 내유외강' },
  { id: 34, beQuestion: '저에게 어울리는 것 : 인만추 Vs 자만추' },
  { id: 35, beQuestion: '저의 최장 연애 기간은 얼마일 것 같나요?' },
  { id: 36, beQuestion: '저는 어떤 이성과 어울릴 것 같나요?' },
  { id: 37, beQuestion: '저에게 가상 이름을 지어주고 그 이유를 알려주세요!' },
  {
    id: 38,
    beQuestion: '제가 꼭 시도해봤으면 하는 패션 아이템을 추천해주세요!',
  },
  { id: 39, beQuestion: '저는 연상, 동갑, 연하 중에 누구와 잘 어울릴까요?' },
  { id: 40, beQuestion: '저와 잘 어울릴 것 같은 장소는 어디인가요?' },
  {
    id: 41,
    beQuestion:
      '저의 가족 내 위치는 어디일까요? ex) 누나 둘 있는 막내, 형 하나 있는 동생',
  },
  { id: 42, beQuestion: '저의 이미지를 한 가지 동사로 서술한다면?' },
  { id: 43, beQuestion: '저에게 하고 싶은 말이 있다면?' },
  { id: 44, beQuestion: '저에게 편지를 써준다면 첫 문장은 어떻게 시작하나요?' },
  { id: 45, beQuestion: '저는 친구들과 있을 때 어떤 포지션을 담당할까요?' },
  { id: 46, beQuestion: '제가 당신을 처음 만났던 순간을 기억하나요?' },
  {
    id: 47,
    beQuestion: '제가 당신과 친하다면, 우린 어떻게 친해질 수 있었을까요?',
  },
  { id: 48, beQuestion: '제 별명은 무엇일까요?' },
  { id: 49, beQuestion: '저에 대해 알고 있는 TMI가 있다면?' },
  { id: 50, beQuestion: '저를 사랑하시나요?' },
  { id: 51, beQuestion: '저에게 어울리는 머리 색은 무엇인가요?' },
  { id: 52, beQuestion: '제 키는 몇 일까요?' },
  { id: 53, beQuestion: '저를 꽃으로 표현한다면 무슨 꽃인가요?' },
  { id: 54, beQuestion: '저를 색깔로 표현한다면?' },
  { id: 55, beQuestion: '제 고향은 어디일까요?' },
  { id: 56, beQuestion: '제가 잘하는 건 무엇일까요?' },
  { id: 57, beQuestion: '제가 못하는 건 무엇일까요?' },
  { id: 58, beQuestion: '제가 가장 많이 사용할 것 같은 어플은 무엇인가요?' },
  { id: 59, beQuestion: '제 휴대폰 배경화면은 무엇일 것 같나요?' },
  { id: 60, beQuestion: '갑자기 저의 부고 소식을 들으면 어떨 것 같나요?' },
  { id: 61, beQuestion: '저희 집 반려 동물 / 반려 식물의 이름은?' },
  { id: 62, beQuestion: '저는 이번 크리스마스에 솔로일까요? 커플일까요?' },
  { id: 63, beQuestion: '저와 함께 멀리 여행 떠나자고 한다면?' },
  { id: 64, beQuestion: '저의 전공은 무엇일까요?' },
  { id: 65, beQuestion: '저의 학창 시절 모습은?' },
  { id: 66, beQuestion: '저에게 직접 전하지 못한 말이 있다면?' },
  {
    id: 67,
    beQuestion: '제가 큰 돈을 부탁한다면 당신은 어떻게 대처할 건가요?',
  },
  { id: 68, beQuestion: '저의 스트레스 해소 방법은 무엇일까요?' },
  { id: 69, beQuestion: '제가 못 먹는 음식은 무엇일까요?' },
  { id: 70, beQuestion: '저는 몇 살처럼 보이나요?' },
  { id: 71, beQuestion: '저는 평소에 말이 많은 편인가요?' },
  { id: 72, beQuestion: '저의 최근 관심사는 무엇일까요?' },
  { id: 73, beQuestion: '저의 몸무게는 몇으로 보이나요?' },
  { id: 74, beQuestion: '저랑 몇 년 동안 알고 지냈나요?' },
  { id: 75, beQuestion: '제가 멋있어 보였던 순간은?' },
  { id: 76, beQuestion: '제가 미웠던 순간은?' },
  { id: 77, beQuestion: '제 목소리는 어떤가요?' },
  { id: 78, beQuestion: '제가 마라탕에 넣을 것 같은 재료는?' },
  { id: 79, beQuestion: '저랑 어울리는 주류는?' },
  { id: 80, beQuestion: '제 주량은 얼마나 될 거 같나요?' },
  { id: 81, beQuestion: '저의 술버릇을 알고 있나요?' },
  { id: 82, beQuestion: '절 제일 보고 싶을 때는 언제인가요?' },
  { id: 83, beQuestion: '제가 풀어준 썰 중에 가장 재미없었던 것은?' },
  { id: 84, beQuestion: '제가 풀어준 썰 중에 가장 재밌었던 것은?' },
  { id: 85, beQuestion: '제가 아이돌로 데뷔하면 담당할 것 같은 포지션은?' },
  { id: 86, beQuestion: '제가 식당 주인이라면 어떤 식당을 운영할 것 같나요?' },
  { id: 87, beQuestion: '‘저’를 떠올리면 생각나는 한 단어는?' },
  { id: 88, beQuestion: '제가 당신에게 건넸던 첫 마디는 무엇이었나요?' },
  { id: 89, beQuestion: '당신이 알고 있는 저의 비밀이 있다면?' },
  {
    id: 90,
    beQuestion: '저 같은 상사 밑에서 일하기 vs  저 같은 부하 직원이랑 일하기',
  },
  { id: 91, beQuestion: '제가 ‘이것’ 만은 고쳤으면 한다면?' },
  { id: 92, beQuestion: '제 모습 중에 배우고 싶은 점이 있다면?' },
  { id: 93, beQuestion: '제가 유튜브를 한다면 보고 싶은 콘텐츠는?' },
  { id: 94, beQuestion: '저에게만 말하고 싶은 당신의 비밀이 있나요?' },
  { id: 95, beQuestion: '당신이 저로 살 수 있다면 가장 먼저 하고 싶은 일은?' },
  { id: 96, beQuestion: '제가 잘할 거 같은 술 게임은?' },
  {
    id: 97,
    beQuestion: '저와 처음 만난 날로 돌아간다면 건네고 싶은 첫 마디는?',
  },
  { id: 98, beQuestion: '저와 함께 보고 싶은 영화는?' },
  {
    id: 99,
    beQuestion: '제가 홍보대사가 된다면 어울리는 브랜드는 무엇인가요?',
  },
  { id: 100, beQuestion: '제가 갑자기 우리 집으로 와 달라고 한다면?' },
  { id: 101, beQuestion: '만약 환생한다면, 저는 무엇으로 태어날 것 같나요?' },
  {
    id: 102,
    beQuestion: '제가 당신보다 10살 어린 동생이었다면 하고 싶은 말은?',
  },
  {
    id: 103,
    beQuestion: '저한테 처음이자 마지막으로 선물을 준다면 무엇을 주고 싶나요?',
  },
  {
    id: 104,
    beQuestion: '제가 로또 1등에 당첨되면 제일 먼저 할 것 같은 일은?',
  },
  { id: 105, beQuestion: '제가 아침마다 거울 보고 생각할 것 같은 말은?' },
  // { id: 106, beQuestion: '' },
];
